import type { Template } from "../types";

export const seedTemplates: Template[] = [
  {
    id: "nexxen-1",
    name: "NEXXEN-1",
    family: "nexxen",
    region: "us-east-1",
    selectedParams: [
      "app_bundle",
      "auction_id",
      "clicktracker",
      "device_id",
      "domain",
      "gdpr",
      "usp",
    ],
    selectedCreativeParams: ["cta"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
  {
    id: "nexxen-2",
    name: "NEXXEN-2",
    family: "nexxen",
    region: "us-east-1",
    selectedParams: [
      "app_bundle",
      "auction_id",
      "device_id",
      "NEXXEN_ZIP_MACRO",
      "Weather_Alpha",
      "percentage_weight",
    ],
    selectedCreativeParams: ["autopop_first", "rand_titles"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
  {
    id: "nexxen-3",
    name: "NEXXEN-3",
    family: "nexxen",
    region: "us-east-1",
    selectedParams: [
      "tag",
      "AppBundle",
      "nonskippable",
      "gdpr",
      "usp",
      "percentage_weight",
    ],
    selectedCreativeParams: ["cta", "player_font"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
  {
    id: "ttd-1",
    name: "TTD-1",
    family: "ttd",
    region: "us-east-1",
    selectedParams: [
      "clicktracer",
      "dealid",
      "device_id",
      "device_type",
      "domain",
    ],
    selectedCreativeParams: ["cta"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
  {
    id: "ttd-2",
    name: "TTD-2",
    family: "ttd",
    region: "us-east-1",
    selectedParams: [
      "TTD_Auction_Macro",
      "TTD_ZIP_DYNAMIC_MACRO",
      "TTD_GENRE_DYNAMIC_MACRO",
      "Weather_Alpha",
      "percentage_weight",
    ],
    selectedCreativeParams: ["autopop_first", "rand_titles"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
  {
    id: "ttd-3",
    name: "TTD-3",
    family: "ttd",
    region: "us-east-1",
    selectedParams: [
      "tag",
      "AdImpression",
      "device_type",
      "nonskippable",
      "percentage_weight",
    ],
    selectedCreativeParams: ["cta", "player_font"],
    customKeyValues: [],
    customMacros: [],
    isBuiltIn: true,
  },
];
